package com.edusyspro.api.entities.enums;

public enum Section {
    MATERNELLE,
    PRIMAIRE,
    COLLEGE,
    LYCEE,
    INSTITUT,
    INSTITUT_TECHNIQUE,
    UNIVERSITE,
    LYCEE_GENERALE,
    LYCEE_TECHNIQUE,
    LYCEE_TECHNIQUE_COMMERCIALE,
    LYCEE_TECHNIQUE_INDUSTRIEL,
    LYCEE_PROFESSIONEL
}
